"""Portable static builder used when the native Astro/esbuild binary is sandboxed."""
from pathlib import Path
from html import escape
import shutil

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
PUBLIC = ROOT / "public"
SITE = "https://boreal-plating.dazum-digital.chatgpt.site"

NAV = {
    "pt": [("Home","/"),("Quem Somos","/quem-somos/"),("O Que Fazemos","/o-que-fazemos/"),("P&D","/ped/"),("ESG","/esg/"),("Certificações","/certificacoes/"),("Contato","/contato/")],
    "en": [("Home","/en/"),("About","/en/about/"),("What We Do","/en/what-we-do/"),("R&D","/en/r-and-d/"),("ESG","/en/esg/"),("Certifications","/en/certifications/"),("Contact","/en/contact/")],
}
PAIRS = {"/":"/en/","/quem-somos/":"/en/about/","/o-que-fazemos/":"/en/what-we-do/","/ped/":"/en/r-and-d/","/esg/":"/en/esg/","/certificacoes/":"/en/certifications/","/contato/":"/en/contact/"}
PAIRS.update({v:k for k,v in list(PAIRS.items())})

def button(label, href, outline=False):
    return f'<a class="button {"button-outline" if outline else ""}" href="{href}">{label} <span>↗</span></a>'

def header(lang, path):
    links = ''.join(f'<a class="{"active" if href == path else ""}" href="{href}">{label}</a>' for label,href in NAV[lang])
    mobile = ''.join(f'<a href="{href}"><span>{i:02}</span>{label}</a>' for i,(label,href) in enumerate(NAV[lang],1))
    alt = PAIRS.get(path, "/en/" if lang == "pt" else "/")
    return f'''<header class="site-header" data-header><div class="header-inner"><a class="brand" href="{'/' if lang=='pt' else '/en/'}" aria-label="Boreal Plating — Home"><img src="/images/logo-boreal.png" width="250" height="78" alt="Boreal Plating"></a><nav class="desktop-nav" aria-label="{'Navegação principal' if lang=='pt' else 'Primary navigation'}">{links}</nav><div class="header-tools"><a class="language" href="{alt}" aria-label="{'View in English' if lang=='pt' else 'Ver em português'}"><span class="{'selected' if lang=='pt' else ''}">PT</span><i></i><span class="{'selected' if lang=='en' else ''}">EN</span></a><a class="social-link" href="https://www.linkedin.com/company/boreal-pecas-industriais" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="{'Abrir menu' if lang=='pt' else 'Open menu'}"><span></span><span></span></button></div></div><div class="mobile-menu" id="mobile-menu" hidden><nav aria-label="{'Navegação móvel' if lang=='pt' else 'Mobile navigation'}">{mobile}</nav><div class="mobile-socials"><a href="https://www.instagram.com/boreal_plating/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/company/boreal-pecas-industriais" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div></header>'''

def footer(lang):
    links = ''.join(f'<li><a href="{href}">{label}</a></li>' for label,href in NAV[lang][1:])
    return f'''<footer class="site-footer"><div class="footer-grid container"><div class="footer-brand"><img src="/images/logo-boreal.png" width="250" height="78" alt="Boreal Plating" loading="lazy"><p>{'Processos industriais integrados com precisão, controle e rastreabilidade.' if lang=='pt' else 'Integrated industrial processes with precision, control and traceability.'}</p></div><div><p class="footer-label">{'Navegação' if lang=='pt' else 'Navigation'}</p><ul>{links}</ul></div><div><p class="footer-label">{'Contato' if lang=='pt' else 'Contact'}</p><address>Rua Tuiuti, 3835 — Aventureiro, Joinville — SC, 89226-001, Brasil</address><a href="tel:+554734199393">+55 (47) 3419-9393</a><a href="mailto:contato@borealnet.com.br">contato@borealnet.com.br</a></div><div><p class="footer-label">{'Acompanhe' if lang=='pt' else 'Follow'}</p><a href="https://www.instagram.com/boreal_plating/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/company/boreal-pecas-industriais" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><div class="footer-bottom container"><span>© 2026 Boreal Plating</span><span>Joinville · Santa Catarina · Brasil</span></div></footer>'''

def hero(eyebrow, title, desc, image, alt):
    return f'''<section class="page-hero"><img class="page-hero-image" src="{image}" alt="{escape(alt)}" width="1800" height="1000" fetchpriority="high"><div class="page-hero-shade"></div><div class="container page-hero-content"><p class="eyebrow light">{eyebrow}</p><h1>{title}</h1><p>{desc}</p></div></section>'''

def cta(lang):
    title = 'Seu projeto exige precisão, controle e capacidade industrial?' if lang=='pt' else 'Does your project require precision, control and industrial capability?'
    return f'''<section class="cta-band reveal"><div class="container cta-inner"><div><p class="eyebrow light">{'CONVERSE COM A BOREAL' if lang=='pt' else 'TALK TO BOREAL'}</p><h2>{title}</h2></div>{button('Fale com nosso time' if lang=='pt' else 'Talk to our team','/contato/' if lang=='pt' else '/en/contact/')}</div></section>'''

def cards(items):
    return '<div class="feature-grid">'+''.join(f'<article class="feature-card reveal"><span class="feature-number">{i:02}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate(items,1))+'</div>'

def process(items):
    return '<div class="process-list">'+''.join(f'<article class="process-item reveal"><h3>{t}</h3><p>{d}</p></article>' for t,d in items)+'</div>'

def documents(items, lang):
    out=''
    for title,desc,href in items:
        out += f'<article class="document-card reveal"><div class="document-icon">PDF</div><div><h3>{title}</h3><p>{desc}</p></div><div class="document-actions"><a href="{href}" target="_blank" rel="noopener noreferrer">{"Ver documento" if lang=="pt" else "View document"} ↗</a><a href="{href}" download>{"Baixar PDF" if lang=="pt" else "Download PDF"} ↓</a></div></article>'
    return '<div class="document-grid">'+out+'</div>'

def shell(lang, path, title, desc, body):
    canonical=SITE+path
    jsonld='{"@context":"https://schema.org","@type":["Organization","LocalBusiness"],"name":"Boreal Plating","url":"'+SITE+'","email":"contato@borealnet.com.br","telephone":"+55 (47) 3419-9393"}'
    js="""<script>const h=document.querySelector('[data-header]'),t=document.querySelector('.menu-toggle'),m=document.querySelector('.mobile-menu');const sh=()=>h&&h.classList.toggle('scrolled',scrollY>24);sh();addEventListener('scroll',sh,{passive:true});t?.addEventListener('click',()=>{const o=t.getAttribute('aria-expanded')==='true';t.setAttribute('aria-expanded',String(!o));if(m)m.hidden=o;document.body.classList.toggle('menu-open',!o)});if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>o.observe(e))}else document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));</script>"""
    return f'''<!doctype html><html lang="{'pt-BR' if lang=='pt' else 'en'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><meta name="theme-color" content="#101827"><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="{'en' if lang=='pt' else 'pt-BR'}" href="{SITE+PAIRS[path]}"><link rel="icon" href="/images/logo-boreal.png" type="image/png"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{canonical}"><link rel="stylesheet" href="/assets/global.css"><title>{escape(title)}</title><script type="application/ld+json">{jsonld}</script></head><body><a class="skip-link" href="#content">{'Ir para o conteúdo' if lang=='pt' else 'Skip to content'}</a>{header(lang,path)}<main id="content">{body}</main>{footer(lang)}{js}</body></html>'''

PT_PROCESS=[('Engenharia','Estudo de viabilidade e desenvolvimento conforme os requisitos do projeto.'),('Matéria-prima','Seleção de materiais de acordo com as especificações técnicas.'),('Usinagem','Fabricação dimensional controlada com precisão e rastreabilidade.'),('Acabamento mecânico','Preparação da superfície para requisitos funcionais e visuais.'),('Plating','Tratamentos químicos e eletrolíticos com controle de parâmetros.'),('Montagem','Integração e conferência conforme a especificação do conjunto.'),('Envio','Inspeção, documentação e expedição conforme os requisitos do cliente.')]
EN_PROCESS=[('Engineering','Feasibility studies and development based on project requirements.'),('Raw material','Material selection in accordance with technical specifications.'),('Machining','Dimensionally controlled manufacturing with precision and traceability.'),('Mechanical finishing','Surface preparation for functional and visual requirements.'),('Plating','Chemical and electrolytic treatments with controlled parameters.'),('Assembly','Integration and checks against assembly specifications.'),('Shipment','Inspection, documentation and dispatch to customer requirements.')]
PT_DOCS=[('Política Ambiental','Diretrizes para prevenção da poluição e melhoria contínua.','/documents/esg/politica-ambiental.pdf'),('Certificado de Energia Renovável 2026','Certificação do consumo de energia de fontes renováveis.','/documents/esg/certificado-energia-renovavel-2026-pt.pdf'),('Certificado de Energia Renovável 2025','Certificação do consumo de energia de fontes renováveis.','/documents/esg/certificado-energia-renovavel-2025-pt.pdf'),('Código de Ética e Conduta','Princípios que orientam a conduta corporativa.','/documents/esg/codigo-de-etica-e-conduta.pdf'),('Relatório de Igualdade Salarial — 1º semestre de 2026','Conforme a Lei nº 14.611/2023.','/documents/esg/relatorio-igualdade-salarial-1-2026.pdf'),('Relatório de Igualdade Salarial — 2º semestre de 2025','Conforme a Lei nº 14.611/2023.','/documents/esg/relatorio-igualdade-salarial-2-2025.pdf')]
EN_DOCS=[('Environmental Policy','Guidelines for pollution prevention and continual improvement.','/documents/esg/politica-ambiental.pdf'),('Renewable Energy Certificate 2026','Certification of renewable electricity consumption.','/documents/esg/renewable-energy-certificate-2026-en.pdf'),('Renewable Energy Certificate 2025','Certification of renewable electricity consumption.','/documents/esg/renewable-energy-certificate-2025-en.pdf'),('Code of Ethics and Conduct','Principles that guide corporate conduct.','/documents/esg/codigo-de-etica-e-conduta.pdf'),('Pay Equity Report — First half of 2026','Publication under Brazilian Law 14.611/2023.','/documents/esg/relatorio-igualdade-salarial-1-2026.pdf'),('Pay Equity Report — Second half of 2025','Publication under Brazilian Law 14.611/2023.','/documents/esg/relatorio-igualdade-salarial-2-2025.pdf')]

def home(lang):
    pt=lang=='pt'; path='/' if pt else '/en/'
    capabilities=[('Tratamento de superfícies','Processos químicos e eletrolíticos com controle de parâmetros, espessura e acabamento.'),('Usinagem','Fabricação dimensional controlada, com precisão, repetibilidade e rastreabilidade.'),('Injeção','Fabricação de peças plásticas e integração com conjuntos industriais.'),('Fabricação e acabamentos','Componentes metálicos, montagem, acabamento mecânico, pintura e vernizes.')] if pt else [('Surface treatment','Chemical and electrolytic processes with controlled parameters, thickness and finish.'),('Machining','Dimensionally controlled manufacturing with precision, repeatability and traceability.'),('Injection molding','Plastic-parts manufacturing and integration with industrial assemblies.'),('Manufacturing and finishing','Metal components, assembly, mechanical finishing, painting and coatings.')]
    body=f'''<section class="home-hero"><img src="/images/peca-industrial.webp" alt="{'Componente industrial com acabamento metálico produzido pela Boreal' if pt else 'Metal-finished industrial component produced by Boreal'}" width="1800" height="1100" fetchpriority="high"><div class="hero-overlay"></div><div class="container hero-content"><p class="eyebrow light">{'ENGENHARIA · PROCESSO · ACABAMENTO' if pt else 'ENGINEERING · PROCESS · FINISHING'}</p><h1>{'Soluções integradas para processos industriais de alta exigência.' if pt else 'Integrated solutions for demanding industrial processes.'}</h1><p class="hero-lead">{'A Boreal reúne tratamento de superfícies, usinagem, injeção e fabricação de componentes em uma operação orientada por precisão e controle.' if pt else 'Boreal brings surface treatment, machining, injection molding and component manufacturing together in an operation built around precision and control.'}</p><div class="hero-actions">{button('Conheça o que fazemos' if pt else 'Explore our capabilities','/o-que-fazemos/' if pt else '/en/what-we-do/')}{button('Fale conosco' if pt else 'Contact us','/contato/' if pt else '/en/contact/',True)}</div></div><div class="hero-index">{'DESDE' if pt else 'SINCE'} 1988</div></section>'''
    body+=f'''<section class="section"><div class="container intro-grid reveal"><div><p class="eyebrow">BOREAL PLATING</p><h2>{'Tradição industrial, precisão e evolução contínua.' if pt else 'Industrial heritage, precision and continuous evolution.'}</h2></div><div class="intro-copy"><p>{'Desde 1988, a Boreal constrói uma trajetória baseada em conhecimento técnico, controle de processos e atenção aos detalhes.' if pt else 'Since 1988, Boreal has built a trajectory grounded in technical knowledge, process control and attention to detail.'}</p><a class="text-link" href="{'/quem-somos/' if pt else '/en/about/'}">{'Conheça nossa história' if pt else 'Discover our history'} →</a></div></div></section>'''
    body+=f'''<section class="section section-ice"><div class="container"><div class="heading-row reveal"><div><p class="eyebrow">{'CAPACIDADE INDUSTRIAL' if pt else 'INDUSTRIAL CAPABILITY'}</p><h2>{'Processos conectados, do desenvolvimento ao acabamento.' if pt else 'Connected processes, from development to finishing.'}</h2></div><p>{'Uma estrutura preparada para integrar etapas e manter requisitos técnicos sob controle.' if pt else 'A structure designed to integrate stages and keep technical requirements under control.'}</p></div>{cards(capabilities)}</div></section>'''
    body+=f'''<section class="section"><div class="container split"><div class="media-frame reveal"><img src="/images/processo-plating.webp" alt="{'Peças metálicas em processo de acabamento' if pt else 'Metal parts during finishing'}" loading="lazy"></div><div class="reveal"><p class="eyebrow">{'PESQUISA & DESENVOLVIMENTO' if pt else 'RESEARCH & DEVELOPMENT'}</p><h2>{'Conhecimento aplicado à melhoria dos processos.' if pt else 'Knowledge applied to better processes.'}</h2><p class="lead">{'Engenharia de superfícies, testes e desenvolvimento contínuo apoiam soluções adequadas aos requisitos de cada projeto.' if pt else 'Surface engineering, testing and continuous development support solutions aligned with each project.'}</p></div></div></section>'''
    body+=f'''<section class="section-tight section-dark"><div class="container editorial-cards"><a class="editorial-card reveal" href="{'/esg/' if pt else '/en/esg/'}"><img src="/images/fachada-boreal.webp" alt="Boreal Plating" loading="lazy"><div><p class="eyebrow light">ESG</p><h3>{'Responsabilidade integrada à operação.' if pt else 'Responsibility integrated into operations.'}</h3><p>{'Gestão ambiental, compromisso social e governança com documentos públicos.' if pt else 'Environmental management, social commitment and governance backed by public documents.'}</p></div></a><a class="editorial-card reveal" href="{'/certificacoes/' if pt else '/en/certifications/'}"><img src="/images/peca-cromada.webp" alt="Chrome finish" loading="lazy"><div><p class="eyebrow light">{'CERTIFICAÇÕES' if pt else 'CERTIFICATIONS'}</p><h3>{'Qualidade validada por padrões reconhecidos.' if pt else 'Quality validated by recognized standards.'}</h3><p>ISO 9001:2015 · AS9100:2016 · Cyber Trust Europe</p></div></a></div></section>{cta(lang)}'''
    title='Boreal Plating | Soluções industriais integradas' if pt else 'Boreal Plating | Integrated industrial solutions'
    desc='Tratamento de superfícies, usinagem, injeção e fabricação de componentes com precisão, controle e rastreabilidade.' if pt else 'Surface treatment, machining, injection molding and component manufacturing with precision, control and traceability.'
    return path,title,desc,body

def internal_pages():
    pages=[]
    about_cards_pt=[('Missão','Ser solução em peças, subconjuntos e sistemas, com qualidade assegurada.'),('Visão','Ser reconhecida pelo desenvolvimento tecnológico, qualidade e alto padrão estético.'),('Valores','Respeito à vida, à ética, às leis, às pessoas e ao ambiente.')]
    about_cards_en=[('Mission','Provide solutions in parts, subassemblies and systems with assured quality.'),('Vision','Be recognized for technological development, quality and high aesthetic standards.'),('Values','Respect for life, ethics, the law, people and the environment.')]
    for lang in ('pt','en'):
        pt=lang=='pt'
        path='/quem-somos/' if pt else '/en/about/'
        body=hero('QUEM SOMOS' if pt else 'ABOUT','Uma trajetória construída com experiência, precisão e evolução.' if pt else 'A trajectory built on experience, precision and evolution.','Desde 1988, conhecimento técnico e atenção aos detalhes orientam a Boreal.' if pt else 'Since 1988, technical knowledge and attention to detail have shaped Boreal.','/images/historia-sede.webp','Vista aérea histórica da sede da Boreal')
        timeline=PT_PROCESS[:0]+[('1988','Início da trajetória em Joinville.' if pt else 'The journey begins in Joinville.'),('1989','Participação dos fundadores no EBRATS.' if pt else 'The founders attend EBRATS.'),('1998','Inauguração da atual sede na Rua Tuiuti.' if pt else 'The current facility opens on Rua Tuiuti.'),('Hoje' if pt else 'Today','Processos integrados para projetos de alta exigência.' if pt else 'Integrated processes for demanding projects.')]
        body+=f'<section class="section"><div class="container intro-grid reveal"><div><p class="eyebrow">{"NOSSA HISTÓRIA" if pt else "OUR HISTORY"}</p><h2>{"Da primeira sede à operação industrial atual." if pt else "From the first site to today’s industrial operation."}</h2></div><div class="intro-copy"><p>{"Fundada em Joinville por dois engenheiros químicos, a Boreal ampliou sua atuação nos setores eletroeletrônico, linha branca, construção civil, automotivo e aeroespacial." if pt else "Founded in Joinville by two chemical engineers, Boreal expanded into the electronics, home-appliance, construction, automotive and aerospace sectors."}</p></div></div></section><section class="section-tight section-ice"><div class="container">{process(timeline)}</div></section>'
        body+=f'<section class="section"><div class="container"><div class="photo-grid"><figure class="wide reveal"><img src="/images/historia-terreno.webp" alt="Historical site" loading="lazy"></figure><figure class="reveal"><img src="/images/historia-instalacoes.webp" alt="Future facilities sign" loading="lazy"></figure><figure class="reveal"><img src="/images/historia-construcao.webp" alt="Plant construction" loading="lazy"></figure><figure class="wide reveal"><img src="/images/historia-sede.webp" alt="Aerial facility view" loading="lazy"></figure></div></div></section><section class="section section-dark"><div class="container">{cards(about_cards_pt if pt else about_cards_en)}</div></section>{cta(lang)}'
        pages.append((lang,path,('Quem Somos' if pt else 'About')+' | Boreal Plating','Trajetória, evolução industrial, princípios e compromisso com qualidade.' if pt else 'Industrial history, evolution, principles and commitment to quality.',body))

        path='/o-que-fazemos/' if pt else '/en/what-we-do/'
        body=hero('O QUE FAZEMOS' if pt else 'WHAT WE DO','Capacidade industrial integrada em cada etapa.' if pt else 'Integrated industrial capability at every stage.','Da engenharia ao envio, fabricação e acabamento com controle de processo.' if pt else 'From engineering to shipment, manufacturing and finishing with process control.','/images/processo-plating.webp','Plating process')
        finishes=['14k Gold','24k Gold','Almond Gold','Antique Nickel','Bronze Dark Aged Antique','Champagne Gold','Chrome','Copper','Crescent Gold','Nickel','Platinum','Rose Gold','Silver','Smoked Nickel']
        body+=f'<section class="section"><div class="container"><div class="heading-row"><div><p class="eyebrow">{"FLUXO DE FORNECIMENTO" if pt else "SUPPLY FLOW"}</p><h2>{"Um processo conectado do início ao fim." if pt else "A connected process from start to finish."}</h2></div></div>{process(PT_PROCESS if pt else EN_PROCESS)}</div></section><section class="section section-dark"><div class="container finish-grid"><div class="media-frame"><img src="/images/amostras-plating.webp" alt="Plating samples" loading="lazy"></div><div><p class="eyebrow light">PLATING</p><h2>{"Variedade de cores e acabamentos." if pt else "A broad range of colors and finishes."}</h2><div class="finish-list">'+''.join(f'<span>{x}</span>' for x in finishes)+f'</div></div></div></section><section class="section"><div class="container split"><div><p class="eyebrow">{"ANODIZAÇÃO E REVESTIMENTOS" if pt else "ANODIZING AND COATINGS"}</p><h2>{"Acabamentos para função e estética." if pt else "Finishes for function and aesthetics."}</h2><p>{"Anodização em preto, champagne, castanho, bronze e natural, além de vernizes e pintura conforme a especificação." if pt else "Anodizing in black, champagne, brown, bronze and natural, plus coatings and painting to specification."}</p></div><div class="media-frame"><img src="/images/amostras-anodizacao.webp" alt="Anodizing samples" loading="lazy"></div></div></section>{cta(lang)}'
        pages.append((lang,path,('O Que Fazemos' if pt else 'What We Do')+' | Boreal Plating','Capacidades industriais integradas da Boreal Plating.' if pt else 'Boreal Plating integrated industrial capabilities.',body))

        path='/ped/' if pt else '/en/r-and-d/'
        rd=[('Ciência e engenharia de superfícies','Pesquisa de novos processos e tecnologias.'),('Laboratórios e confiabilidade','Testes, caracterização e análises de superfície.'),('Parcerias técnicas','Colaboração com universidades e centros de pesquisa.')] if pt else [('Surface science and engineering','Research into new processes and technologies.'),('Laboratories and reliability','Testing, characterization and surface analysis.'),('Technical partnerships','Collaboration with universities and research centers.')]
        body=hero('PESQUISA & DESENVOLVIMENTO' if pt else 'RESEARCH & DEVELOPMENT','Engenharia aplicada ao processo produtivo.' if pt else 'Engineering applied to production.','Conhecimento técnico transformado em melhorias de processo.' if pt else 'Technical knowledge turned into process improvements.','/images/peca-dourada.webp','Metal finish')+f'<section class="section"><div class="container intro-grid"><div><p class="eyebrow">P&D</p><h2>{"Pesquisa conectada às necessidades da indústria." if pt else "Research connected to industrial needs."}</h2></div><p>{"Caracterização de materiais, análises e avaliações de desempenho apoiam a melhoria contínua." if pt else "Material characterization, analysis and performance evaluation support continual improvement."}</p></div></section><section class="section section-ice"><div class="container">{cards(rd)}</div></section>{cta(lang)}'
        pages.append((lang,path,('Pesquisa e Desenvolvimento' if pt else 'Research and Development')+' | Boreal Plating','Pesquisa, engenharia de superfícies e melhoria contínua.' if pt else 'Research, surface engineering and continual improvement.',body))

        path='/esg/' if pt else '/en/esg/'
        pillars=[('Ambiental','Gestão ambiental, energia e prevenção de impactos.'),('Social','Respeito, ética e transparência nas relações.'),('Governança','Conformidade, integridade e segurança da informação.')] if pt else [('Environmental','Environmental management, energy and impact prevention.'),('Social','Respect, ethics and transparency in relationships.'),('Governance','Compliance, integrity and information security.')]
        body=hero('ESG','Responsabilidade integrada à forma de operar.' if pt else 'Responsibility integrated into the way we operate.','Compromissos ambientais, sociais e de governança documentados.' if pt else 'Documented environmental, social and governance commitments.','/images/fachada-boreal.webp','Boreal facility')+f'<section class="section"><div class="container">{cards(pillars)}</div></section><section class="section section-ice"><div class="container"><div class="heading-row"><div><p class="eyebrow">{"DOCUMENTOS E RELATÓRIOS" if pt else "DOCUMENTS AND REPORTS"}</p><h2>{"Compromissos documentados." if pt else "Documented commitments."}</h2></div></div>{documents(PT_DOCS if pt else EN_DOCS,lang)}</div></section>{cta(lang)}'
        pages.append((lang,path,'ESG | Boreal Plating','Práticas ambientais, sociais e de governança.' if pt else 'Environmental, social and governance practices.',body))

        path='/certificacoes/' if pt else '/en/certifications/'
        certs=[('ISO 9001:2015','Certificado nº 67548 · válido até 29/06/2027','/documents/certifications/iso-9001-2015-boreal-plating.pdf'),('AS9100:2016','Certificado nº 62482 · válido até 31/05/2027','/documents/certifications/as9100-2016-boreal-plating.pdf'),('Cyber Trust Europe — Silver Label','Válido até 22/04/2027','/documents/certifications/cyber-trust-europe-label-2026.pdf')]
        body=hero('CERTIFICAÇÕES' if pt else 'CERTIFICATIONS','Qualidade sustentada por padrões reconhecidos.' if pt else 'Quality supported by recognized standards.','Certificações ativas apoiam disciplina, rastreabilidade e melhoria contínua.' if pt else 'Active certifications support discipline, traceability and continual improvement.','/images/peca-cromada.webp','Chrome finished parts')+f'<section class="section"><div class="container intro-grid"><div><p class="eyebrow">{"QUALIDADE E CONFORMIDADE" if pt else "QUALITY AND COMPLIANCE"}</p><h2>{"Critérios técnicos incorporados à rotina." if pt else "Technical criteria embedded in everyday operations."}</h2></div><p>{"Sistemas e práticas avaliados por organismos independentes." if pt else "Systems and practices assessed by independent bodies."}</p></div></section><section class="section section-ice"><div class="container">{documents(certs,lang)}</div></section>{cta(lang)}'
        pages.append((lang,path,('Certificações' if pt else 'Certifications')+' | Boreal Plating','Certificações ISO 9001, AS9100 e Cyber Trust Europe.' if pt else 'ISO 9001, AS9100 and Cyber Trust Europe certifications.',body))

        path='/contato/' if pt else '/en/contact/'
        form=f'''<form class="contact-form" data-contact-form><div class="form-field"><label for="contact-name">{'Nome' if pt else 'Name'} *</label><input id="contact-name" name="name" autocomplete="name" required></div><div class="form-field"><label for="contact-company">{'Empresa' if pt else 'Company'} *</label><input id="contact-company" name="company" autocomplete="organization" required></div><div class="form-field"><label for="contact-role">{'Cargo' if pt else 'Role'}</label><input id="contact-role" name="role" autocomplete="organization-title"></div><div class="form-field"><label for="contact-email">{'E-mail' if pt else 'Email'} *</label><input id="contact-email" name="email" type="email" autocomplete="email" required></div><div class="form-field"><label for="contact-phone">{'Telefone' if pt else 'Phone'}</label><input id="contact-phone" name="phone" type="tel" autocomplete="tel"></div><div class="form-field"><label for="contact-subject">{'Assunto' if pt else 'Subject'} *</label><input id="contact-subject" name="subject" required></div><div class="form-field full"><label for="contact-message">{'Mensagem' if pt else 'Message'} *</label><textarea id="contact-message" name="message" required></textarea></div><label class="consent"><input type="checkbox" required><span>{'Autorizo o uso dos dados para o retorno desta solicitação.' if pt else 'I authorize the use of this data to respond to my request.'}</span></label><div class="form-field full"><button class="button" type="submit">{'Enviar mensagem' if pt else 'Send message'} ↗</button></div><p class="form-note" data-form-status>{'Formulário preparado para integração com a plataforma de atendimento da Boreal.' if pt else 'Form prepared for integration with Boreal’s customer-service platform.'}</p></form><script>document.querySelector('[data-contact-form]').addEventListener('submit',e=>{{e.preventDefault();if(e.currentTarget.reportValidity())e.currentTarget.querySelector('[data-form-status]').textContent='{'Mensagem validada. O envio será ativado após a integração do canal de atendimento.' if pt else 'Message validated. Sending will be enabled after customer-service integration.'}'}})</script>'''
        body=hero('CONTATO' if pt else 'CONTACT','Vamos conversar sobre o seu projeto.' if pt else "Let's talk about your project.",'Compartilhe os requisitos técnicos ou comerciais da sua necessidade.' if pt else 'Share the technical or commercial requirements of your application.','/images/recepcao-boreal.webp','Boreal entrance')+f'<section class="section"><div class="container contact-grid"><div><p class="eyebrow">{"CONTATO COMERCIAL" if pt else "SALES CONTACT"}</p><h2>{"Informação técnica começa com uma conversa objetiva." if pt else "Technical information starts with a focused conversation."}</h2><div class="contact-list"><div class="contact-item"><span>{"Endereço" if pt else "Address"}</span><p>Rua Tuiuti, 3835 — Aventureiro, Joinville — SC, 89226-001, Brasil</p></div><div class="contact-item"><span>{"Telefone" if pt else "Phone"}</span><a href="tel:+554734199393">+55 (47) 3419-9393</a></div><div class="contact-item"><span>Email</span><a href="mailto:contato@borealnet.com.br">contato@borealnet.com.br</a></div></div></div>{form}</div></section><iframe class="map-frame" title="Boreal Plating map" loading="lazy" src="https://www.google.com/maps?q=Rua%20Tuiuti%203835%20Joinville%20SC&output=embed"></iframe>'
        pages.append((lang,path,('Contato' if pt else 'Contact')+' | Boreal Plating','Contato técnico e comercial com a Boreal Plating.' if pt else 'Technical and sales contact with Boreal Plating.',body))
    return pages

def build():
    if DIST.exists(): shutil.rmtree(DIST)
    shutil.copytree(PUBLIC,DIST)
    (DIST/'assets').mkdir(exist_ok=True)
    shutil.copy2(ROOT/'src/styles/global.css',DIST/'assets/global.css')
    pages=[('pt',*home('pt')),('en',*home('en'))]+internal_pages()
    for lang,path,title,desc,body in pages:
        out=DIST/('index.html' if path=='/' else path.strip('/')+'/index.html')
        out.parent.mkdir(parents=True,exist_ok=True)
        out.write_text(shell(lang,path,title,desc,body),encoding='utf-8')
    shutil.copy2(ROOT/'.openai/hosting.json',DIST/'.openai-hosting.json')
    print(f'Built {len(pages)} pages in {DIST}')

if __name__=='__main__': build()
